Repository decide-single-hierro1/decide-single-hierro1, pull requests merged in 2022-12, with the labels that each got.

#33 feat: Creación métodos api
  decide/visualizer/metrics.py
  decide/visualizer/urls.py
  decide/visualizer/views.py
Labels: enhancement

#34 4 paginacion
  .gitignore
  decide/visualizer/templates/visualizer/all.html
Labels: enhancement

#36 4 paginacion
  decide/visualizer/templates/visualizer/all.html
Labels: enhancement

#39 feat: Add discord notification
  .github/workflows/django.yml
Labels: documentation, enhancement

#40 30 creación métodos api
  decide/visualizer/urls.py
  decide/visualizer/views.py
Labels: bug

#44 feat: Add plotting module
  decide/visualizer/plots.py
  requirements.txt
Labels: enhancement
